# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_state\
$nodejs\
$cmd_duration\
$line_break\
$character"""

add_newline = false 

[character] 
success_symbol = "[](bold green) " 
error_symbol = "[✗](bold red) "

[package]
disabled = true
